### ISSUE TITLE
Need more documentation

### ISSUE THREAD

**Issue by thomas-illiet** [faroutchris/cast-server#5]
Hello @faroutchris,

I really appreciate finding a recent project to create a chromecast server.

Can you add more documentation to use your projet ?
because actually i'm unable to start this project :/

Kind regards
Thomas

**Comment by che-122** [comment]
Sorry bro, this project doesn't do anything interesting, it's just an abandoned project that wraps a few functions from https://github.com/xat/chromecast-player with nodejs/express

**Comment by thomas-illiet** [comment]
Ok no problem actually i search method/project to create proxy to remove youtube pub ( ads )
A keep your project in my starts :)
